export async function GET() {
  return Response.json({
    players: [
      {
        name: "Cristiano Ronaldo",
        team: "Portugal",
        position: "FWD",
        minutes: 90,
        xg: 0.42,
        xa: 0.05,
        shots: 4,
        keyPasses: 1,
        passesCompletedPct: 78,
        duelsWonPct: 45,
        tackles: 0,
        interceptions: 0,
        matchRating: 7.2
      },
      {
        name: "Bruno Fernandes",
        team: "Portugal",
        position: "MID",
        minutes: 90,
        xg: 0.10,
        xa: 0.25,
        shots: 2,
        keyPasses: 3,
        passesCompletedPct: 86,
        duelsWonPct: 52,
        tackles: 2,
        interceptions: 1,
        matchRating: 6.8
      },
      {
        name: "Nuno Mendes",
        team: "Portugal",
        position: "DEF",
        minutes: 120,
        xg: 0.05,
        xa: 0.10,
        shots: 1,
        keyPasses: 1,
        passesCompletedPct: 84,
        duelsWonPct: 80,
        tackles: 4,
        interceptions: 2,
        matchRating: 8.1
      },
      {
        name: "Diogo Costa",
        team: "Portugal",
        position: "GK",
        minutes: 120,
        xg: 0,
        xa: 0,
        shots: 0,
        keyPasses: 0,
        passesCompletedPct: 81,
        duelsWonPct: 0,
        tackles: 0,
        interceptions: 0,
        matchRating: 7.0
      },
      {
        name: "Lamine Yamal",
        team: "Spain",
        position: "FWD",
        minutes: 106,
        xg: 0.20,
        xa: 0.15,
        shots: 4,
        keyPasses: 2,
        passesCompletedPct: 82,
        duelsWonPct: 61,
        tackles: 1,
        interceptions: 0,
        matchRating: 7.2
      },
      {
        name: "Zubimendi",
        team: "Spain",
        position: "MID",
        minutes: 120,
        xg: 0.64,
        xa: 0.05,
        shots: 2,
        keyPasses: 1,
        passesCompletedPct: 94,
        duelsWonPct: 67,
        tackles: 2,
        interceptions: 1,
        matchRating: 7.8
      },
      {
        name: "Cucurella",
        team: "Spain",
        position: "DEF",
        minutes: 120,
        xg: 0.03,
        xa: 0.05,
        shots: 0,
        keyPasses: 0,
        passesCompletedPct: 88,
        duelsWonPct: 70,
        tackles: 2,
        interceptions: 2,
        matchRating: 6.9
      },
      {
        name: "Unai Simón",
        team: "Spain",
        position: "GK",
        minutes: 120,
        xg: 0,
        xa: 0,
        shots: 0,
        keyPasses: 0,
        passesCompletedPct: 79,
        duelsWonPct: 0,
        tackles: 0,
        interceptions: 0,
        matchRating: 5.6
      }
    ]
  });
}
