"use client";
import { useCallback, useEffect, useState } from "react";

const tone = (value) => value === "ready" || value === "A" || value === "WATCH" ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-100" : value === "blocked" || value === "D" || value === "SKIP" ? "border-rose-400/40 bg-rose-400/10 text-rose-100" : "border-amber-400/40 bg-amber-400/10 text-amber-100";
function Badge({ children }) { return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${tone(children)}`}>{children}</span>; }
function Stat({ label, value, help }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs uppercase tracking-[.16em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold text-white">{value ?? "—"}</p>{help ? <p className="mt-1 text-xs text-slate-500">{help}</p> : null}</div>; }

export default function ProductionControlCenterClient() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [hours, setHours] = useState("720");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const res = await fetch(`/api/production-control-center?hours=${hours}`, { cache: "no-store" }); const body = await res.json(); if (!res.ok || !body.ok) throw new Error(body.error || "Unavailable"); setData(body); } catch (e) { setError(e.message || "Production Control Center could not be loaded"); } finally { setLoading(false); } }, [hours]);
  useEffect(() => { load(); }, [load]);
  const r = data?.readiness; const c = data?.calibration; const clv = data?.closingLine;
  return <main className="mx-auto max-w-7xl space-y-7 px-4 py-8 text-slate-100 sm:px-6">
    <section className="rounded-3xl border border-white/10 bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 p-7 shadow-2xl">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.24em] text-indigo-300">Scorecaster Production Control Center</p><h1 className="mt-3 text-3xl font-bold sm:text-5xl">Yksi näkymä tuotantovalmiuteen</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">Collectorin tuoreus, Daily Top 3, mallien kalibrointi, closing line ja riskiblokkerit samassa paper-only-ohjaamossa.</p></div><div className="flex gap-2"><Badge>{r?.status || (loading ? "loading" : "unknown")}</Badge><Badge>paper-only</Badge></div></div>
    </section>
    <div className="flex flex-wrap gap-3"><select value={hours} onChange={e=>setHours(e.target.value)} className="rounded-xl border border-white/10 bg-slate-950 px-4 py-2"><option value="168">7 päivää</option><option value="720">30 päivää</option><option value="2160">90 päivää</option><option value="8760">1 vuosi</option></select><button onClick={load} className="rounded-xl border border-indigo-300/30 bg-indigo-300/10 px-4 py-2 font-semibold text-indigo-100">Päivitä</button></div>
    {error ? <div className="rounded-2xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-100">{error}</div> : null}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Stat label="Valmiuspisteet" value={r?.score}/><Stat label="Tapahtumat" value={data?.summary?.events}/><Stat label="Lähteet" value={data?.summary?.sources}/><Stat label="Kalibroitu" value={c?.count}/><Stat label="Brier Score" value={c?.brier}/><Stat label="Closing line" value={clv?.count}/></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-slate-950/70 p-6"><h2 className="text-xl font-semibold">Tuotantoblokkerit</h2><div className="mt-4 space-y-2">{(r?.blockers||[]).map(x=><div key={x} className="rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-100">{x}</div>)}{r?.blockers?.length===0?<div className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-emerald-100">Ei aktiivisia blokkereita.</div>:null}</div></div><div className="rounded-3xl border border-white/10 bg-slate-950/70 p-6"><h2 className="text-xl font-semibold">Kalibrointi</h2><div className="mt-4 grid grid-cols-2 gap-3"><Stat label="Luokka" value={c?.grade}/><Stat label="Log loss" value={c?.logLoss}/><Stat label="Calibration error" value={c?.calibrationError}/><Stat label="Näytteet" value={c?.count}/></div></div></section>
    <section className="rounded-3xl border border-white/10 bg-slate-950/70 p-6"><h2 className="text-xl font-semibold">Daily Top 3</h2><div className="mt-5 grid gap-4 lg:grid-cols-3">{(data?.dailyTop3||[]).map((p,i)=><article key={p.eventId} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex justify-between"><span className="font-bold">#{i+1}</span><Badge>{p.decision}</Badge></div><p className="mt-3 truncate font-semibold" title={p.eventId}>{p.eventId}</p><p className="mt-3 text-3xl font-bold">{p.score}</p><div className="mt-3 text-sm text-slate-300">Malli {(p.modelProbability*100).toFixed(1)} % · markkina {(p.marketProbability*100).toFixed(1)} % · edge {(p.edge*100).toFixed(1)} %</div><p className="mt-3 text-xs leading-5 text-slate-400">{p.reason}</p></article>)}{!loading&&data?.dailyTop3?.length===0?<p className="text-slate-400">Riittävää tapahtumadataa ei vielä ole.</p>:null}</div></section>
    <section className="rounded-3xl border border-white/10 bg-slate-950/70 p-6"><h2 className="text-xl font-semibold">Mallien vertailu</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Malli</th><th className="p-3">Luokka</th><th className="p-3">Pisteet</th><th className="p-3">Tapahtumat</th><th className="p-3">Confidence</th><th className="p-3">Trust</th></tr></thead><tbody>{(data?.models||[]).map(m=><tr key={m.metric} className="border-t border-white/5"><td className="p-3 font-medium">{m.name}</td><td className="p-3"><Badge>{m.grade}</Badge></td><td className="p-3">{m.score}</td><td className="p-3">{m.events}</td><td className="p-3">{m.confidence}</td><td className="p-3">{m.trust}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-amber-300/25 bg-amber-300/10 p-5 text-sm text-amber-50">Daily Top 3 on analyysi- ja paperiseurantalista. Järjestelmä ei aseta vetoja, siirrä rahaa, muuta tuotantotodennäköisyyksiä eikä nosta valintaa PLAY-tilaan.</section>
  </main>;
}
